### ISSUE TITLE
Creates a new process on each start

### ISSUE THREAD

**Issue by Hounddog** [lmammino/prerender-daemon#1]
I am currently investigating on our server that each time we run

service prerender start

It starts a new process even if one is already running. 
I am trying to figure out currently how to solve this.

**Comment by lmammino** [comment]
Hello @hounddog.
Please keep me updated about this, especially if there's some issue with the configuration script that defines the service.

**Comment by Hounddog** [comment]
It currently looks like the pid itself is incorrect

**Comment by Hounddog** [comment]
Actually no. it creates the correct pid and the pidfile but then it just starts the process over and over again.

**Comment by Hounddog** [comment]
I just checked this on another system and has the exact same issue.
It just starts a new process even though there is already a process running.
The pid and pidfile are correct.

It seems cause -exec is creating using /usr/bin/prerender
However the process name is "node /usr/bin/prerender"

**Comment by Hounddog** [comment]
ubuntu@ip-10-0-0-248:/etc/init.d$ sudo service prerender start
- Starting prerender...                                                                                                                                                                                                           [ OK ]
  ubuntu@ip-10-0-0-248:/etc/init.d$ tail /var/run/prerender/prerender.pid
  14278
  ubuntu@ip-10-0-0-248:/etc/init.d$ ps -ax | grep prerender
  14278 ?        Sl     0:00 node /usr/bin/prerender
  14280 ?        Sl     0:00 /usr/bin/nodejs /usr/bin/prerender
  14286 ?        Sl     0:00 /usr/local/lib/node_modules/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1 /usr/local/lib/node_modules/prerender/node_modules/phantom/shim.js 12301 127.0.0.1
  14292 pts/0    S+     0:00 grep --color=auto prerender
  ubuntu@ip-10-0-0-248:/etc/init.d$ sudo service prerender start
- Starting prerender...                                                                                                                                                                                                           [ OK ]
  ubuntu@ip-10-0-0-248:/etc/init.d$ tail /var/run/prerender/prerender.pid
  14312
  ubuntu@ip-10-0-0-248:/etc/init.d$ ps -ax | grep prerender
  14278 ?        Sl     0:00 node /usr/bin/prerender
  14280 ?        Sl     0:00 /usr/bin/nodejs /usr/bin/prerender
  14286 ?        Sl     0:00 /usr/local/lib/node_modules/prerender/node_modules/phantomjs/lib/phantom/bin/phantomjs --load-images=false --ignore-ssl-errors=true --ssl-protocol=tlsv1 /usr/local/lib/node_modules/prerender/node_modules/phantom/shim.js 12301 127.0.0.1
  14312 ?        Sl     0:00 node /usr/bin/prerender
  14416 ?        Rl     0:00 /usr/bin/nodejs /usr/bin/prerender
  14419 pts/0    S+     0:00 grep --color=auto prerender

**Comment by Hounddog** [comment]
The solution is in this article
https://chris-lamb.co.uk/posts/start-stop-daemon-exec-vs-startas

Instead of --exec we need to use --startas

**Comment by Hounddog** [comment]
Provided a patch for this in #2

**Comment by lmammino** [comment]
Fixed with #2
